name: mount

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  mount:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 5
    strategy:
      matrix:
        operating-system: [macos-10.15, macos-11, macos-12]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: go build -o mountefi

    - name: Show Volumes
      run: ./mountefi volumes

    - name: Mount volume
      run: ./mountefi mount "Macintosh HD"
